name: Publish a new release

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published]

jobs:
  verify-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r nox-requirements.txt

      - name: Check versions
        run: python -m nox -s check-versions -- -r ${{ github.event.release.tag_name }}

  publish-docs:
    needs: verify-version
    runs-on: ubuntu-latest

    steps:
      - name: Fetch and clone the master branch
        uses: actions/checkout@v2
        with:
          path: ./master_branch
          ref: master

      - name: Fetch and clone the docs branch
        uses: actions/checkout@v2
        with:
          path: ./docs_branch
          ref: docs

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: |
          cd ./master_branch
          python -m pip install --upgrade pip wheel
          python -m pip install -r nox-requirements.txt

      - name: Build docs
        id: doc_info
        run: |
          cd ./master_branch
          mkdir docs
          python -m nox -s generate-docs -- -o ./docs -j
          echo "::set-output name=GIT_HASH::$(git rev-parse HEAD)"
          cd ..
          rm -r ./docs_branch/release
          cp -r ./master_branch/docs ./docs_branch/release

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: ./docs_branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Release docs: ${{ github.event.release.tag_name }} (${{ steps.doc_info.outputs.GIT_HASH }})"

  publish:
    needs: verify-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r nox-requirements.txt

      - name: publish
        run: python -m nox -s publish -- -u __token__ -p ${{ secrets.PYPI_TOKEN }} -i ${{ secrets.PYPI_TARGET }} --skip-version-check
