name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@cd7d8d697e10461458bc61a30d094dc601a8b017
        with:
          submodules: "true"

      - name: Set up Python 3.9
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: "3.9"

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./piped/python/base-requirements/nox.txt

      - name: Build docs
        id: doc_info
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site -j
          echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_STATE

      - name: Push
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e
        with:
          branch: docs
          commit-message: "${{ steps.doc_info.outputs.GIT_HASH }} docs (${{ github.event.release.tag_name || github.event.ref }})"
          clean-exclude: pr-preview
          folder: ./site
          git-config-email: "120557446+always-on-duty[bot]@users.noreply.github.com"
          git-config-name: "always-on-duty[bot]"
