name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: "true"

      - name: Install Python
        uses: ./.github/actions/setup-py

      - name: Build docs
        id: doc_info
        run: |
          mkdir site
          nox -s generate-docs -- -o ./site -j
          echo "GIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_STATE

      - name: Push
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8
        with:
          branch: docs
          commit-message: "${{ steps.doc_info.outputs.GIT_HASH }} docs (${{ github.event.release.tag_name || github.event.ref }})"
          clean-exclude: pr-preview
          folder: ./site
          git-config-email: "120557446+always-on-duty[bot]@users.noreply.github.com"
          git-config-name: "always-on-duty[bot]"
