name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: "true"

      - name: Set up Python 3.9
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: "3.9"

      - name: Install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./piped/python/base-requirements/nox.txt

      - name: Build docs
        id: doc_info
        run: |
          mkdir site
          python -m nox -s generate-docs -- -o ./site -j
          echo "::set-output name=GIT_HASH::$(git rev-parse HEAD)"

      - name: Push
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6
        with:
          branch: docs
          commit-message: "${{ steps.doc_info.outputs.GIT_HASH }} docs (${{ github.event.release.tag_name || github.event.ref }})"
          clean-exclude: pr-preview
          folder: ./site
          git-config-email: "120557446+always-on-duty[bot]@users.noreply.github.com"
          git-config-name: "always-on-duty[bot]"
