name: Upgrade dev dependencies

on:
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

jobs:
  upgrade-dev-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r ./dev-requirements/nox.txt

      - name: Upgrade dev dependencies
        run: python -m nox -s upgrade-dev-deps

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: task/upgrade-dev-deps
          commit-message: Upgrade dev dependencies
          title: Upgrade dev dependencies
